name: deps
on:
  schedule:
    # Normaly every 10:00, every day
    # Now every hour for testing
    # - cron: '0 10 * * *' # At 10:00, every day
    - cron: '0 * * * *' # Every hour, every day

jobs:
  zsh-async:
    name: Update zsh-async
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v2
        with:
          # FIXME: Remove this when 4.x is merged
          # See: https://stackoverflow.com/a/58800550/5508862
          ref: 4.x

      - name: 👀 Check zsh-async Releases
        id: zsh-async
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/mafredri/zsh-async/releases/latest | jq -r  ".tag_name")
          echo ::set-output name=current_tag::$(grep '# version:' ./lib/async.zsh | cut -d':' -f2 | xargs)

      - name: 📦 Update zsh-async
        if: steps.zsh-async.outputs.current_tag != steps.zsh-async.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.zsh-async.outputs.release_tag }}
        run: |
          # Download the release
          curl -sL -o $RELEASE_TAG https://api.github.com/repos/mafredri/zsh-async/tarball/$RELEASE_TAG

          # Extract a async.zsh file from the release
          tar -xzvf $RELEASE_TAG --strip-components=1 $(tar -tzf $RELEASE_TAG | head -1 | cut -f1 -d"/")/async.zsh

          # Remove archive
          rm $RELEASE_TAG

      - name: ↩️ Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            build(zsh-async): Update zsh-async to ${{ steps.zsh-async.outputs.release_tag }}
          title: |
            Update zsh-async to ${{ steps.zsh-async.outputs.release_tag }}
          body: |
            Updates [zsh-async][1] to ${{ steps.zsh-async.outputs.release_tag }}

            [1]: https://github.com/mafredri/zsh-async
          labels: async, dependencies
          branch: zsh-async-update
          branch-suffix: ${{ steps.zsh-async.outputs.release_tag }}
          delete-branch: true
